import uuid
from typing import Optional
from sqlalchemy import Float, ForeignKey, Integer, String, Text, Uuid, JSON
from sqlalchemy.orm import Mapped, mapped_column
from lens.database import LensBase, LensTimestampMixin, LensUUIDMixin


class SN1Thread(LensUUIDMixin, LensTimestampMixin, LensBase):
    """LangGraph execution thread for persistent agent workflows (Section 28, 52)."""
    __tablename__ = "lens_sn1_threads"

    tenant_id: Mapped[str] = mapped_column(String(64), index=True, default="default_tenant")
    student_id: Mapped[uuid.UUID] = mapped_column(Uuid(as_uuid=True), index=True, nullable=False)
    thread_key: Mapped[str] = mapped_column(String(255), unique=True, index=True, nullable=False)


class SN1Run(LensUUIDMixin, LensTimestampMixin, LensBase):
    """Execution run record for SN1 autonomous agent iterations (Section 28, 55)."""
    __tablename__ = "lens_sn1_runs"

    thread_id: Mapped[uuid.UUID] = mapped_column(Uuid(as_uuid=True), ForeignKey("lens_sn1_threads.id", ondelete="CASCADE"), index=True)
    student_id: Mapped[uuid.UUID] = mapped_column(Uuid(as_uuid=True), index=True, nullable=False)
    trigger_type: Mapped[str] = mapped_column(String(64), nullable=False) # benchmark_completed, quiz_completed, bottleneck_changed, student_query, manual
    status: Mapped[str] = mapped_column(String(32), default="running") # running, completed, interrupted, failed
    
    state_snapshot_json: Mapped[dict] = mapped_column(JSON, default=dict)
    plan_json: Mapped[dict] = mapped_column(JSON, default=dict)
    output_summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    execution_time_ms: Mapped[int] = mapped_column(Integer, default=0)


class SN1DecisionAudit(LensUUIDMixin, LensTimestampMixin, LensBase):
    """Explainable audit trail for every action taken by SN1 (Section 55)."""
    __tablename__ = "lens_sn1_decision_audits"

    decision_id: Mapped[uuid.UUID] = mapped_column(Uuid(as_uuid=True), default=uuid.uuid4, index=True)
    run_id: Mapped[Optional[uuid.UUID]] = mapped_column(Uuid(as_uuid=True), nullable=True)
    student_id: Mapped[uuid.UUID] = mapped_column(Uuid(as_uuid=True), index=True, nullable=False)
    
    trigger: Mapped[str] = mapped_column(String(64), nullable=False)
    bottleneck: Mapped[str] = mapped_column(String(64), nullable=False)
    candidate_actions_json: Mapped[list] = mapped_column(JSON, default=list)
    selected_action_json: Mapped[dict] = mapped_column(JSON, default=dict)
    policy_result_json: Mapped[dict] = mapped_column(JSON, default=dict)
    tool_calls_json: Mapped[list] = mapped_column(JSON, default=list)
    execution_result_json: Mapped[dict] = mapped_column(JSON, default=dict)


class TeacherEscalationAlert(LensUUIDMixin, LensTimestampMixin, LensBase):
    """Explainable alerts generated by SN1 for human teacher intervention (Section 42)."""
    __tablename__ = "lens_teacher_escalations"

    tenant_id: Mapped[str] = mapped_column(String(64), index=True, default="default_tenant")
    student_id: Mapped[uuid.UUID] = mapped_column(Uuid(as_uuid=True), index=True, nullable=False)
    concept_id: Mapped[Optional[uuid.UUID]] = mapped_column(Uuid(as_uuid=True), nullable=True)
    
    escalation_reason: Mapped[str] = mapped_column(String(128), nullable=False) # persistent_misconception, repeated_failure, low_progress_velocity, high_uncertainty
    severity: Mapped[str] = mapped_column(String(32), default="MEDIUM") # LOW, MEDIUM, HIGH, CRITICAL
    details_json: Mapped[dict] = mapped_column(JSON, default=dict)
    status: Mapped[str] = mapped_column(String(32), default="OPEN") # OPEN, IN_REVIEW, RESOLVED, DISMISSED
    resolved_by: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
